[package]
name = "kdtree-iced"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = ["canvas"] }

[dev-dependencies]
rand = "0.9.2"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "docs/katex-header.html" ]
